src/ConverterKoppu/Models/Converter.cs
using System.ComponentModel.DataAnnotations;

namespace ConverterKoppu.Models
{
    public class Converter
    {
        public int ConverterID { get; set; }

        [Display(Name = "ZIP Code")]
        [RegularExpression(@"^\d{5}(?:[-\s]\d{4})?$", ErrorMessage = "Please enter a valid US ZIP code")]
        public int Zipcode { get; set; } = 64468;

        [Required]
        [Range(-12, 200)]
        [Display(Name = "Temperature (F)")]
        public int Temperature_F { get; set; } = 72;
    }
}

src/ConverterKoppu/Controllers/ConverterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using ConverterKoppu.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace ConverterKoppu.Controllers
{
    public class ConverterController : Controller
    {
        public IActionResult Koppu()
        {
            ViewData["Title"] = "Converter App by Koppu";
            ViewData["Result"] = "";

            Converter converter = new Converter();
            return View(converter);
        }

        public IActionResult Convert(Converter converter)
        {
            if (ModelState.IsValid)
            {
                ViewData["Title"] = "Converted by Koppu";
                ViewData["Value"] = (int)((converter.Temperature_F - 32) * 5.0 / 9.0);
                ViewData["Result"] = "Temperature in C = " +
                    (int)((converter.Temperature_F - 32) * 5.0 / 9.0);
                
            }
            return View("Koppu", converter);
        }
    }
}

src/ConverterKoppu/Views/Converter/Koppu.cshtml
@model ConverterKoppu.Models.Converter

<h2>@ViewData["Title"]</h2>
<div class="col-xs-12">
    <form asp-controller="Converter" asp-action="Convert" method="post" class="form-horizontal" role="form">

        <div class="form-group">
            <label asp-for="Zipcode" class="control-label"></label>
            <input asp-for="Zipcode" class="form-control" />
            <span asp-validation-for="Zipcode" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Temperature_F"></label>
            <input asp-for="Temperature_F" class="form-control" />
            <span asp-validation-for="Temperature_F" class="text-danger"></span>
        </div>

        <div class="form-group">
            <input type="submit" value="Convert" class="btn btn-info" />
        </div>

    </form>
</div>

<h2>@ViewData["Result"]</h2>
<script>
    if(@ViewData["Value"] < 11){
        document.body.style.backgroundImage = "url(http://images.clipartof.com/Royalty-Free-RF-Clipart-Illustration-Of-A-Shivering-Winter-Toon-Guy-Hugging-Himself-To-Keep-Warm-102493476.jpg)"

    }
    else if (@ViewData["Value"] >=11 && @ViewData["Value"] <=25){
        document.body.style.backgroundImage = "url(http://theridgewoodblog.net/wp-content/uploads/2015/07/hot-sun-cooling1_Content.jpg)";
    }
    else{
        document.body.style.backgroundImage = "url(http://www.toptenpack.com/wp-content/uploads/2014/06/wallpaper-spring.jpg)";
    }
</script>

src/ConverterKoppu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConverterKoppu</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                    <a asp-controller="Converter" asp-action="Koppu" class="navbar-brand">ConverterKoppu</a>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />*@
        <footer>
            <p>&copy; 2016 - ConverterKoppu</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>